'use client';

import Link from 'next/link';
import { ChangeEvent, useEffect, useState } from 'react';
import * as XLSX from 'xlsx';
import { collection, doc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore';
import { ArrowLeft, CheckCircle2, FileSpreadsheet, Loader2, Upload, XCircle } from 'lucide-react';
import { db } from '@/lib/firebase';
import { getCurrentUser, SessionUser } from '@/lib/session';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import NoAccess from '@/components/no-access';

type RouteInfo = { id:string; routeNo:string; edoId:string; site:string; description?:string };
type ReconRow = { routeNo:string; sourceName:string; routeId?:string; edoId?:string; matched:boolean; reconDate:string; allowance:number; previousOutstanding:number; issuedToday:number; returnedToday:number; currentOutstanding:number; dollyPreviousOutstanding:number; dollyIssuedToday:number; dollyReturnedToday:number; dollyCurrentOutstanding:number };
type ParsedSheetRow = { routeNo:string; sourceName:string; allowance?:number; previousOutstanding:number; issuedToday:number; returnedToday:number; currentOutstanding:number };
const cleanSite=(v:unknown)=>String(v??'').trim().toLowerCase();
const iso=(v:unknown)=>{if(v instanceof Date&&!Number.isNaN(v.getTime()))return`${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}-${String(v.getDate()).padStart(2,'0')}`;if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);if(d)return`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`;}const s=String(v??'').trim();const d=new Date(s);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0}; const outstanding=(v:unknown)=>Math.abs(num(v)); const routeKey=(v:unknown)=>String(v??'').trim().toUpperCase().replace(/\s+/g,''); const docSafe=(v:string)=>v.replace(/[^A-Za-z0-9_-]/g,'-');
function findDateGroup(rows:unknown[][],selectedDate:string,startCol:number){const h=rows[3]||[];for(let c=startCol;c<h.length;c++)if(iso(h[c])===selectedDate)return c;return-1}
function availableDates(rows:unknown[][],startCol:number){const s=new Set<string>();const h=rows[3]||[];for(let c=startCol;c<h.length;c++){const d=iso(h[c]);if(d)s.add(d)}return[...s].sort()}
function parseSheet(rows:unknown[][],selectedDate:string,kind:'crate'|'dolly'):ParsedSheetRow[]{const start=kind==='crate'?4:3,c=findDateGroup(rows,selectedDate,start);if(c<0)return[];const prev=c-1,res:ParsedSheetRow[]=[];for(let r=4;r<rows.length;r++){const row=rows[r]||[],routeNo=String(row[0]??'').trim();if(!routeNo||!/^R/i.test(routeNo))continue;const opening=kind==='crate'?3:2;res.push({routeNo,sourceName:String(row[1]??'').trim(),allowance:kind==='crate'?Math.max(0,num(row[2])):undefined,previousOutstanding:outstanding(prev>=start?row[prev]:row[opening]),issuedToday:Math.max(0,num(row[c])),returnedToday:Math.max(0,num(row[c+1])),currentOutstanding:outstanding(row[c+3])})}return res}

export default function PremierReconUploadPage(){
 const[user,setUser]=useState<SessionUser|null>(null),[authLoading,setAuthLoading]=useState(true),[routes,setRoutes]=useState<RouteInfo[]>([]),[workbook,setWorkbook]=useState<XLSX.WorkBook|null>(null),[fileName,setFileName]=useState(''),[dates,setDates]=useState<string[]>([]),[selectedDate,setSelectedDate]=useState(''),[selectedSite,setSelectedSite]=useState('waltloo'),[rows,setRows]=useState<ReconRow[]>([]),[message,setMessage]=useState(''),[importing,setImporting]=useState(false),[skipUnmatched,setSkipUnmatched]=useState(false);
 useEffect(()=>{(async()=>{try{const u=await getCurrentUser();setUser(u);if(u?.userType==='taskraft'){const[rs,cs]=await Promise.all([getDocs(collection(db,'routes')),getDocs(collection(db,'companies'))]);const companySite=new Map(cs.docs.map(d=>[d.id,cleanSite(d.data().site)]));setRoutes(rs.docs.map(d=>{const x=d.data();return{id:d.id,routeNo:String(x.routeNo??''),edoId:String(x.edoId??''),site:cleanSite(x.site)||companySite.get(String(x.edoId??''))||'',description:x.description}}));}}finally{setAuthLoading(false)}})()},[]);
 const sites=[...new Set(routes.map(r=>r.site).filter(Boolean))].sort();
 function parseWorkbook(wb:XLSX.WorkBook,date:string,site=selectedSite){const cs=wb.Sheets['Own Routes Crates'],ds=wb.Sheets['Own Routes Dollies'];if(!cs||!ds){setRows([]);setMessage('Workbook must contain Own Routes Crates and Own Routes Dollies sheets.');return}const crates=XLSX.utils.sheet_to_json<unknown[]>(cs,{header:1,raw:false,defval:null}),dollies=XLSX.utils.sheet_to_json<unknown[]>(ds,{header:1,raw:false,defval:null}),cr=parseSheet(crates,date,'crate'),dr=parseSheet(dollies,date,'dolly'),dm=new Map(dr.map(x=>[routeKey(x.routeNo),x]));const scoped=routes.filter(r=>r.site===cleanSite(site)),rm=new Map(scoped.map(x=>[routeKey(x.routeNo),x]));setRows(cr.map(c=>{const d=dm.get(routeKey(c.routeNo)),route=rm.get(routeKey(c.routeNo));return{routeNo:c.routeNo,sourceName:c.sourceName,routeId:route?.id,edoId:route?.edoId,matched:!!route,reconDate:date,allowance:c.allowance??0,previousOutstanding:c.previousOutstanding,issuedToday:c.issuedToday,returnedToday:c.returnedToday,currentOutstanding:c.currentOutstanding,dollyPreviousOutstanding:d?.previousOutstanding??0,dollyIssuedToday:d?.issuedToday??0,dollyReturnedToday:d?.returnedToday??0,dollyCurrentOutstanding:d?.currentOutstanding??0}}));setMessage('');setSkipUnmatched(false)}
 async function onFile(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setMessage('');setRows([]);const data=await f.arrayBuffer(),wb=XLSX.read(data,{type:'array',cellDates:true}),cs=wb.Sheets['Own Routes Crates'];if(!cs){setMessage('Own Routes Crates sheet not found.');return}const ar=XLSX.utils.sheet_to_json<unknown[]>(cs,{header:1,raw:false,defval:null}),ds=availableDates(ar,4),latest=ds[ds.length-1]||'';setWorkbook(wb);setFileName(f.name);setDates(ds);setSelectedDate(latest);if(latest)parseWorkbook(wb,latest);else setMessage('No reconciliation dates were found in row 4 of Own Routes Crates.')}
 function changeDate(v:string){setSelectedDate(v);if(workbook)parseWorkbook(workbook,v)} function changeSite(v:string){setSelectedSite(v);if(workbook&&selectedDate)parseWorkbook(workbook,selectedDate,v)}
 const matchedRows=rows.filter(r=>r.matched),unmatchedRows=rows.filter(r=>!r.matched),matched=matchedRows.length,unmatched=unmatchedRows.length,canImport=matched>0&&(unmatched===0||skipUnmatched)&&!!user&&user.userType==='taskraft';
 async function importRecon(){if(!canImport||!user)return;setImporting(true);setMessage('');try{for(const r of matchedRows){const id=`${docSafe(r.routeNo)}_${r.reconDate}`;await setDoc(doc(db,'crateReconDaily',id),{routeNo:r.routeNo,routeId:r.routeId,edoId:r.edoId,site:selectedSite,sourceName:r.sourceName,reconDate:r.reconDate,crate:{allowance:r.allowance,previousOutstanding:r.previousOutstanding,issuedToday:r.issuedToday,returnedToday:r.returnedToday,currentOutstanding:r.currentOutstanding},dolly:{previousOutstanding:r.dollyPreviousOutstanding,issuedToday:r.dollyIssuedToday,returnedToday:r.dollyReturnedToday,currentOutstanding:r.dollyCurrentOutstanding},source:'premier_recon',sourceFileName:fileName,importedAt:serverTimestamp(),importedBy:user.uid,importedByName:user.name},{merge:true})}setMessage(`Imported ${matchedRows.length} matched ${selectedSite} route records for ${selectedDate}.${unmatched?` Skipped ${unmatched} unmatched workbook routes.`:''}`)}catch(e){setMessage(e instanceof Error?e.message:'Import failed.')}finally{setImporting(false)}}
 if(authLoading)return<div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin"/></div>;if(!user||user.userType!=='taskraft')return<NoAccess/>;
 return <div className="space-y-6"><Button asChild variant="ghost" className="-ml-3"><Link href="/accounting/crate-control"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Crate & Dolly Control</Link></Button><div><h1 className="text-3xl font-bold">Upload Premier Crate Recon</h1><p className="text-muted-foreground">Match the Premier workbook only against the selected Premier site before importing.</p></div>
 <Card><CardHeader><CardTitle>Import Scope</CardTitle><CardDescription>Select the site first. A Waltloo import will only match routes belonging to current Waltloo EDOs; routes from other sites cannot accidentally match.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div><label className="text-sm font-medium">Premier site</label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={selectedSite} onChange={e=>changeSite(e.target.value)}>{sites.length?sites.map(s=><option key={s} value={s}>{s.replace(/\b\w/g,x=>x.toUpperCase())}</option>):<option value="waltloo">Waltloo</option>}</select></div>{dates.length>0&&<div><label className="text-sm font-medium">Reconciliation date</label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={selectedDate} onChange={e=>changeDate(e.target.value)}>{[...dates].reverse().map(d=><option key={d} value={d}>{d}</option>)}</select></div>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Select Premier Workbook</CardTitle><CardDescription>Nothing is saved until you review the route matching and confirm the import.</CardDescription></CardHeader><CardContent className="space-y-4"><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed p-5 hover:bg-muted/40"><FileSpreadsheet className="h-7 w-7"/><div className="flex-1"><div className="font-medium">{fileName||'Choose .xlsx / .xls file'}</div><div className="text-sm text-muted-foreground">Expected sheets: Own Routes Crates and Own Routes Dollies</div></div><input className="hidden" type="file" accept=".xlsx,.xls" onChange={onFile}/></label>{message&&<div className="rounded-lg border bg-muted/40 p-3 text-sm">{message}</div>}</CardContent></Card>
 {rows.length>0&&<><div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="pt-6"><div className="text-sm text-muted-foreground">Workbook Routes</div><div className="text-3xl font-bold">{rows.length}</div></CardContent></Card><Card><CardContent className="pt-6"><div className="flex items-center gap-2 text-sm text-muted-foreground"><CheckCircle2 className="h-4 w-4 text-emerald-600"/>Matched {selectedSite}</div><div className="text-3xl font-bold text-emerald-700">{matched}</div></CardContent></Card><Card><CardContent className="pt-6"><div className="flex items-center gap-2 text-sm text-muted-foreground"><XCircle className="h-4 w-4 text-red-600"/>Not matched to {selectedSite}</div><div className={`text-3xl font-bold ${unmatched?'text-red-700':'text-emerald-700'}`}>{unmatched}</div></CardContent></Card></div>
 <Card><CardHeader><CardTitle>Import Preview — {selectedDate}</CardTitle><CardDescription>Only matched routes will ever be written. Unmatched workbook routes can be deliberately skipped after review.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-3 text-left">Route</th><th className="text-left">Premier Name</th><th className="text-center">{selectedSite} Match</th><th className="text-right">Allowance</th><th className="text-right">Previous</th><th className="text-right">OUT</th><th className="text-right">IN</th><th className="text-right">Current</th><th className="text-right">Dolly Previous</th><th className="text-right">Dolly OUT</th><th className="text-right">Dolly IN</th><th className="pr-3 text-right">Dolly Current</th></tr></thead><tbody>{rows.map(r=><tr key={r.routeNo} className={`border-b ${!r.matched?'bg-muted/30':''}`}><td className="p-3 font-medium">{r.routeNo}</td><td>{r.sourceName}</td><td className="text-center">{r.matched?<span className="font-semibold text-emerald-700">Matched</span>:<span className="font-semibold text-muted-foreground">Skip</span>}</td><td className="text-right">{r.allowance}</td><td className="text-right">{r.previousOutstanding}</td><td className="text-right">{r.issuedToday}</td><td className="text-right">{r.returnedToday}</td><td className="text-right font-semibold">{r.currentOutstanding}</td><td className="text-right">{r.dollyPreviousOutstanding}</td><td className="text-right">{r.dollyIssuedToday}</td><td className="text-right">{r.dollyReturnedToday}</td><td className="pr-3 text-right font-semibold">{r.dollyCurrentOutstanding}</td></tr>)}</tbody></table></div>
 {unmatched>0&&<label className="mt-5 flex items-start gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4"><input type="checkbox" className="mt-1 h-4 w-4" checked={skipUnmatched} onChange={e=>setSkipUnmatched(e.target.checked)}/><div><div className="font-semibold text-amber-900">I have reviewed the {unmatched} unmatched routes and agree to skip them</div><div className="text-sm text-amber-800">Only the {matched} routes matched to {selectedSite} EDOs will be imported. The unmatched routes will not be written to Firebase.</div></div></label>}
 <div className="mt-5 flex flex-wrap items-center gap-3"><Button onClick={importRecon} disabled={!canImport||importing}>{importing?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Upload className="mr-2 h-4 w-4"/>}Import {matched} Matched Routes</Button>{unmatched>0&&!skipUnmatched&&<span className="text-sm text-amber-800">Review the unmatched routes and tick the skip confirmation to continue.</span>}</div></CardContent></Card></>}
 </div>;
}
