import { NextRequest, NextResponse } from 'next/server';
import { getAdminDb } from '@/lib/firebase-admin';
import { STAFF_SESSION_COOKIE, validateStaffSession } from '@/lib/staff-session';

type WorkWeek='5_day'|'6_day';
function workingDays(from:string,to:string,workWeek:WorkWeek){const start=new Date(`${from}T12:00:00+02:00`),end=new Date(`${to}T12:00:00+02:00`);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||start>end)return 0;let n=0;for(const d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const day=d.getDay();if(workWeek==='6_day'?day!==0:day!==0&&day!==6)n++}return n}
function serialiseDate(v:any){if(!v)return null;if(typeof v.toDate==='function')return v.toDate().toISOString();return String(v)}
export async function GET(request:NextRequest){try{const token=request.cookies.get(STAFF_SESSION_COOKIE)?.value??'';const session=await validateStaffSession(token);if(!session)return NextResponse.json({success:false,message:'Unauthorised.'},{status:401});const db=await getAdminDb();const [empSnap,leaveSnap]=await Promise.all([db.collection('employees').doc(session.employeeId).get(),db.collection('leaveRequests').where('employeeId','==',session.employeeId).get()]);if(!empSnap.exists)return NextResponse.json({success:false,message:'Employee not found.'},{status:404});const e=empSnap.data()||{};const requests=leaveSnap.docs.map(d=>{const x=d.data();return{id:d.id,leaveType:String(x.leaveType||''),fromDate:String(x.fromDate||''),toDate:String(x.toDate||''),days:Number(x.days||0),reason:String(x.reason||''),status:String(x.status||'pending'),requestedAt:serialiseDate(x.requestedAt),approvedAt:serialiseDate(x.approvedAt),rejectedAt:serialiseDate(x.rejectedAt),rejectionReason:String(x.rejectionReason||''),documentName:String(x.documentName||'')}}).sort((a,b)=>(b.fromDate||'').localeCompare(a.fromDate||''));return NextResponse.json({success:true,balance:{annualLeave:Number(e.sageAnnualLeaveBalance??0),period:String(e.sageLeaveBalancePeriod||''),updatedAt:serialiseDate(e.sageLeaveBalanceUpdatedAt)},workWeek:String(e.workWeek||'').toLowerCase()==='6_day'?'6_day':'5_day',requests})}catch(error){console.error('Staff leave load failed:',error);return NextResponse.json({success:false,message:'Unable to load leave information.'},{status:500})}}
export async function POST(request:NextRequest){try{const token=request.cookies.get(STAFF_SESSION_COOKIE)?.value??'';const session=await validateStaffSession(token);if(!session)return NextResponse.json({success:false,message:'Unauthorised.'},{status:401});const body=await request.json();const leaveType=String(body.leaveType||''),fromDate=String(body.fromDate||''),toDate=String(body.toDate||''),reason=String(body.reason||'').trim(),documentName=String(body.documentName||'').trim();if(!['annual_leave','sick_leave','family_responsibility','unpaid_leave'].includes(leaveType))return NextResponse.json({success:false,message:'Select a valid leave type.'},{status:400});if(!/^\d{4}-\d{2}-\d{2}$/.test(fromDate)||!/^\d{4}-\d{2}-\d{2}$/.test(toDate)||fromDate>toDate)return NextResponse.json({success:false,message:'Select a valid leave date range.'},{status:400});const db=await getAdminDb();const empSnap=await db.collection('employees').doc(session.employeeId).get();if(!empSnap.exists)return NextResponse.json({success:false,message:'Employee not found.'},{status:404});const e=empSnap.data()||{};const workWeek:WorkWeek=String(e.workWeek||'').toLowerCase()==='6_day'?'6_day':'5_day',days=workingDays(fromDate,toDate,workWeek);if(days<1)return NextResponse.json({success:false,message:'The selected dates contain no scheduled working days.'},{status:400});const ref=await db.collection('leaveRequests').add({employeeId:session.employeeId,employeeCode:String(e.employeeCode||''),employeeName:[e.firstName,e.surname].filter(Boolean).join(' '),edoId:String(e.edoId||session.edoId||''),edoName:String(e.edoName||session.businessName||''),site:String(e.site||''),leaveType,fromDate,toDate,days,reason,workWeek,status:'pending',source:'employee_portal',documentName:documentName||null,requestedAt:new Date(),approvedAt:null,approvedBy:null,approvedByName:null,rejectedAt:null,rejectedBy:null,rejectedByName:null,rejectionReason:null});return NextResponse.json({success:true,id:ref.id,days})}catch(error){console.error('Staff leave request failed:',error);return NextResponse.json({success:false,message:'Unable to submit leave request.'},{status:500})}}
