'use client';
import Link from 'next/link';import {useEffect,useMemo,useState} from 'react';import {collection,getDocs,query,where} from 'firebase/firestore';import {db} from '@/lib/firebase';import {getCurrentUser,SessionUser} from '@/lib/session';import {Card,CardContent,CardDescription,CardHeader,CardTitle} from '@/components/ui/card';import {Button} from '@/components/ui/button';import {FileWarning,Users,CheckCircle,AlertTriangle,Activity,Loader2,ArrowRight} from 'lucide-react';
type Invoice={id:string;edoId?:string;amount?:number};type LeaveRequest={id:string;edoId?:string;status?:string;days?:number};type Employee={id:string;edoId?:string;occupation?:string;status?:string};type Company={id:string;name?:string;type?:string};
function money(v:number){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',minimumFractionDigits:2}).format(v||0)}function isWorker(e:Employee){return String(e.status||'').trim().toLowerCase()==='employed'&&String(e.occupation||'').trim().toLowerCase()!=='edo'}
export default function DashboardPage(){const[user,setUser]=useState<SessionUser|null>(null),[loading,setLoading]=useState(true),[invoiceLoading,setInvoiceLoading]=useState(true),[leaveLoading,setLeaveLoading]=useState(true),[complianceLoading,setComplianceLoading]=useState(true),[invoiceError,setInvoiceError]=useState(''),[leaveError,setLeaveError]=useState(''),[complianceError,setComplianceError]=useState(''),[pendingInvoices,setPendingInvoices]=useState<Invoice[]>([]),[pendingLeave,setPendingLeave]=useState<LeaveRequest[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[companies,setCompanies]=useState<Company[]>([]);
useEffect(()=>{async function load(){try{const current=await getCurrentUser();setUser(current);if(!current)return;const edoId=current.companyId||current.edoId||'';
try{const r=collection(db,'invoices');if(current.userType==='edo'&&!edoId)throw new Error('Your EDO company is not linked to this user account.');const s=await getDocs(current.userType==='edo'?query(r,where('edoId','==',edoId),where('status','==','pending')):query(r,where('status','==','pending')));setPendingInvoices(s.docs.map(d=>({id:d.id,...d.data()} as Invoice)))}catch(e){setInvoiceError(e instanceof Error?e.message:'Unable to load pending invoices.')}finally{setInvoiceLoading(false)}
try{const r=collection(db,'leaveRequests');const s=await getDocs(current.userType==='edo'?query(r,where('edoId','==',edoId)):r);setPendingLeave(s.docs.map(d=>({id:d.id,...d.data()} as LeaveRequest)).filter(x=>String(x.status||'pending').toLowerCase()==='pending'))}catch(e){setLeaveError(e instanceof Error?e.message:'Unable to load leave requests.')}finally{setLeaveLoading(false)}
try{const er=collection(db,'employees');const es=await getDocs(current.userType==='edo'?query(er,where('edoId','==',edoId)):er);setEmployees(es.docs.map(d=>({id:d.id,...d.data()} as Employee)));if(current.userType==='taskraft'){const cs=await getDocs(collection(db,'companies'));setCompanies(cs.docs.map(d=>{const x=d.data();return{id:String(x.id||d.id),name:String(x.name||''),type:String(x.type||'')}}).filter(x=>x.type==='edo'))}}catch(e){setComplianceError(e instanceof Error?e.message:'Unable to load employee compliance.')}finally{setComplianceLoading(false)}}finally{setLoading(false)}}load()},[]);
const pendingTotal=useMemo(()=>pendingInvoices.reduce((s,x)=>s+Number(x.amount||0),0),[pendingInvoices]),pendingLeaveDays=useMemo(()=>pendingLeave.reduce((s,x)=>s+Number(x.days||0),0),[pendingLeave]),pendingLeaveCompanies=useMemo(()=>new Set(pendingLeave.map(x=>x.edoId).filter(Boolean)).size,[pendingLeave]);const counts=useMemo(()=>{const m=new Map<string,number>();employees.filter(isWorker).forEach(e=>m.set(String(e.edoId||''),(m.get(String(e.edoId||''))||0)+1));return m},[employees]);const isEdo=user?.userType==='edo',edoCount=isEdo?counts.get(String(user?.companyId||user?.edoId||''))||0:0,edoCompliant=edoCount>=3,network=companies.map(c=>({id:c.id,count:counts.get(c.id)||0})),compliantCount=network.filter(x=>x.count>=3).length,nonCompliantCount=network.filter(x=>x.count<3).length;
if(loading)return <div className="flex min-h-[240px] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin"/></div>;
return <div className="flex flex-col gap-8"><header><h1 className="text-3xl font-bold tracking-tight">Dashboard</h1><p className="text-muted-foreground">{isEdo?'Your current business actions and employee status.':'Current operational actions across BizCentral.'}</p></header><div className="grid gap-4 md:grid-cols-3">
<Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Pending Invoices</CardTitle><FileWarning className="h-4 w-4 text-amber-600"/></CardHeader><CardContent>{invoiceLoading?<Loader2 className="h-5 w-5 animate-spin"/>:invoiceError?<p className="text-sm text-red-600">{invoiceError}</p>:<><div className="text-3xl font-bold">{pendingInvoices.length}</div><p className="mt-1 text-sm text-muted-foreground">{pendingInvoices.length?`${money(pendingTotal)} awaiting approval`:'No invoices awaiting approval'}</p><Button asChild variant="link" className="mt-3 h-auto p-0"><Link href="/invoicing/reliever/approve">{pendingInvoices.length?'Review pending invoices':'Open invoicing'}<ArrowRight className="ml-1 h-4 w-4"/></Link></Button></>}</CardContent></Card>
<Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Leave Requests</CardTitle><Users className={`h-4 w-4 ${pendingLeave.length?'text-amber-600':'text-green-600'}`}/></CardHeader><CardContent>{leaveLoading?<Loader2 className="h-5 w-5 animate-spin"/>:leaveError?<p className="text-sm text-red-600">{leaveError}</p>:<><div className="text-3xl font-bold">{pendingLeave.length}</div><p className="mt-1 text-sm text-muted-foreground">{pendingLeave.length===0?'No leave requests awaiting review':isEdo?`${pendingLeaveDays} leave day${pendingLeaveDays===1?'':'s'} awaiting review`:`Across ${pendingLeaveCompanies} EDO compan${pendingLeaveCompanies===1?'y':'ies'}`}</p><Button asChild variant="link" className="mt-3 h-auto p-0"><Link href="/people/leave">{pendingLeave.length?'Review leave requests':'Open leave register'}<ArrowRight className="ml-1 h-4 w-4"/></Link></Button></>}</CardContent></Card>
<Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Employee Compliance</CardTitle>{complianceLoading?<Loader2 className="h-4 w-4 animate-spin"/>:(isEdo?edoCompliant:nonCompliantCount===0)?<CheckCircle className="h-4 w-4 text-green-600"/>:<AlertTriangle className="h-4 w-4 text-red-600"/>}</CardHeader><CardContent>{complianceError?<p className="text-sm text-red-600">{complianceError}</p>:isEdo?<><div className={`text-2xl font-bold ${edoCompliant?'text-green-700':'text-red-700'}`}>{edoCompliant?'Compliant':'Action Required'}</div><p className="mt-1 text-sm text-muted-foreground">{edoCount} employed employee{edoCount===1?'':'s'} • Minimum requirement: 3</p>{!edoCompliant&&<p className="mt-1 text-sm font-medium text-red-600">{3-edoCount} employee{3-edoCount===1?'':'s'} below requirement</p>}<Button asChild variant="link" className="mt-3 h-auto p-0"><Link href="/people">View employees<ArrowRight className="ml-1 h-4 w-4"/></Link></Button></>:<><div className={`text-2xl font-bold ${nonCompliantCount===0?'text-green-700':'text-red-700'}`}>{compliantCount} / {network.length} Compliant</div><p className="mt-1 text-sm text-muted-foreground">{nonCompliantCount===0?'All EDO businesses meet employee minimum':`${nonCompliantCount} EDO business${nonCompliantCount===1?'':'es'} require attention`}</p><Button asChild variant="link" className="mt-3 h-auto p-0"><Link href="/people">Review compliance<ArrowRight className="ml-1 h-4 w-4"/></Link></Button></>}</CardContent></Card></div>
<Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="h-5 w-5"/>Activity</CardTitle><CardDescription>Leave activity, upcoming staff leave and administrator messages will appear here.</CardDescription></CardHeader><CardContent><div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Activity feed will be connected next.</div></CardContent></Card></div>}
