'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { getCurrentUser, SessionUser } from '@/lib/session';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileWarning, Users, CheckCircle, Activity, Loader2, ArrowRight } from 'lucide-react';

type Invoice={id:string;edoId?:string;edoName?:string;amount?:number;status?:string};
type LeaveRequest={id:string;edoId?:string;edoName?:string;employeeId?:string;employeeName?:string;status?:string;fromDate?:string;toDate?:string;days?:number;leaveType?:string};
function money(value:number){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',minimumFractionDigits:2}).format(value||0)}

export default function DashboardPage(){
 const[user,setUser]=useState<SessionUser|null>(null),[loading,setLoading]=useState(true),[invoiceLoading,setInvoiceLoading]=useState(true),[leaveLoading,setLeaveLoading]=useState(true),[invoiceError,setInvoiceError]=useState(''),[leaveError,setLeaveError]=useState(''),[pendingInvoices,setPendingInvoices]=useState<Invoice[]>([]),[pendingLeave,setPendingLeave]=useState<LeaveRequest[]>([]);
 useEffect(()=>{async function loadDashboard(){try{const current=await getCurrentUser();setUser(current);if(!current)return;const edoId=current.companyId||current.edoId||'';
  try{setInvoiceLoading(true);const ref=collection(db,'invoices');if(current.userType==='edo'&&!edoId)throw new Error('Your EDO company is not linked to this user account.');const q=current.userType==='edo'?query(ref,where('edoId','==',edoId),where('status','==','pending')):query(ref,where('status','==','pending'));const snap=await getDocs(q);setPendingInvoices(snap.docs.map(d=>({id:d.id,...d.data()} as Invoice)))}catch(e){console.error('Dashboard invoice load failed:',e);setInvoiceError(e instanceof Error?e.message:'Unable to load pending invoices.')}finally{setInvoiceLoading(false)}
  try{setLeaveLoading(true);const ref=collection(db,'leaveRequests');if(current.userType==='edo'&&!edoId)throw new Error('Your EDO company is not linked to this user account.');const q=current.userType==='edo'?query(ref,where('edoId','==',edoId)):ref;const snap=await getDocs(q);const rows=snap.docs.map(d=>({id:d.id,...d.data()} as LeaveRequest)).filter(r=>String(r.status||'pending').toLowerCase()==='pending');setPendingLeave(rows)}catch(e){console.error('Dashboard leave load failed:',e);setLeaveError(e instanceof Error?e.message:'Unable to load leave requests.')}finally{setLeaveLoading(false)}
 }finally{setLoading(false)}}loadDashboard()},[]);
 const pendingTotal=useMemo(()=>pendingInvoices.reduce((s,x)=>s+Number(x.amount||0),0),[pendingInvoices]);const pendingLeaveDays=useMemo(()=>pendingLeave.reduce((s,x)=>s+Number(x.days||0),0),[pendingLeave]);const pendingLeaveCompanies=useMemo(()=>new Set(pendingLeave.map(x=>x.edoId).filter(Boolean)).size,[pendingLeave]);
 if(loading)return <div className="flex min-h-[240px] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground"/></div>;
 const isEdo=user?.userType==='edo';
 return <div className="flex flex-col gap-8"><header><h1 className="text-3xl font-bold tracking-tight">Dashboard</h1><p className="text-muted-foreground">{isEdo?'Your current business actions and employee status.':'Current operational actions across BizCentral.'}</p></header>
 <div className="grid gap-4 md:grid-cols-3">
  <Card className="transition-shadow hover:shadow-md"><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Pending Invoices</CardTitle><FileWarning className="h-4 w-4 text-amber-600"/></CardHeader><CardContent>{invoiceLoading?<Loader2 className="h-5 w-5 animate-spin text-muted-foreground"/>:invoiceError?<p className="text-sm text-red-600">{invoiceError}</p>:<><div className="text-3xl font-bold">{pendingInvoices.length}</div><p className="mt-1 text-sm text-muted-foreground">{pendingInvoices.length===0?'No invoices awaiting approval':`${money(pendingTotal)} awaiting approval`}</p><Button asChild variant="link" className="mt-3 h-auto p-0"><Link href="/invoicing/reliever/approve">{pendingInvoices.length?'Review pending invoices':'Open invoicing'}<ArrowRight className="ml-1 h-4 w-4"/></Link></Button></>}</CardContent></Card>
  <Card className="transition-shadow hover:shadow-md"><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Leave Requests</CardTitle><Users className={`h-4 w-4 ${pendingLeave.length?'text-amber-600':'text-green-600'}`}/></CardHeader><CardContent>{leaveLoading?<Loader2 className="h-5 w-5 animate-spin text-muted-foreground"/>:leaveError?<p className="text-sm text-red-600">{leaveError}</p>:<><div className="text-3xl font-bold">{pendingLeave.length}</div><p className="mt-1 text-sm text-muted-foreground">{pendingLeave.length===0?'No leave requests awaiting review':isEdo?`${pendingLeaveDays} leave day${pendingLeaveDays===1?'':'s'} awaiting review`:`Across ${pendingLeaveCompanies} EDO compan${pendingLeaveCompanies===1?'y':'ies'}`}</p><Button asChild variant="link" className="mt-3 h-auto p-0"><Link href="/people/leave">{pendingLeave.length?'Review leave requests':'Open leave register'}<ArrowRight className="ml-1 h-4 w-4"/></Link></Button></>}</CardContent></Card>
  <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Employee Compliance</CardTitle><CheckCircle className="h-4 w-4 text-muted-foreground"/></CardHeader><CardContent><div className="text-3xl font-bold text-muted-foreground">—</div><p className="mt-1 text-sm text-muted-foreground">Employee compliance is next</p></CardContent></Card>
 </div>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="h-5 w-5"/>Activity</CardTitle><CardDescription>Leave activity, upcoming staff leave and administrator messages will appear here.</CardDescription></CardHeader><CardContent><div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Activity feed will be connected after the dashboard action cards.</div></CardContent></Card></div>
}
