'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { collection, getDocs, orderBy, query } from 'firebase/firestore';
import { ArrowLeft, AlertTriangle, Download, FileSpreadsheet, Loader2, Settings, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { db } from '@/lib/firebase';
import { getCurrentUser, SessionUser } from '@/lib/session';

type ReplacementRate={id:string;crateCost:number;dollyCost:number;effectiveFrom:string};
type Recon={id:string;routeNo:string;edoId?:string;site?:string;sourceName?:string;reconDate:string;crate:{allowance:number;previousOutstanding:number;issuedToday:number;returnedToday:number;currentOutstanding:number};dolly:{previousOutstanding:number;issuedToday:number;returnedToday:number;currentOutstanding:number}};
const money=(v:number)=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',minimumFractionDigits:2}).format(v||0);
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(new Date(`${v}T00:00:00`).getTime());
const prettyDate=(v:string)=>{if(!validDate(v))return v;const d=new Date(`${v}T00:00:00`);return d.toLocaleDateString('en-ZA',{day:'numeric',month:'short',year:'numeric'})};
const daysBefore=(v:string,days:number)=>{if(!validDate(v))return'';const d=new Date(`${v}T00:00:00`);d.setDate(d.getDate()-days);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const csvCell=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;
export default function CrateControlPage(){
 const[user,setUser]=useState<SessionUser|null>(null),[rates,setRates]=useState<ReplacementRate[]>([]),[recons,setRecons]=useState<Recon[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selectedRoute,setSelectedRoute]=useState(''),[fromDate,setFromDate]=useState(''),[toDate,setToDate]=useState('');
 useEffect(()=>{(async()=>{try{const u=await getCurrentUser();setUser(u);const[rateSnap,reconSnap]=await Promise.all([getDocs(query(collection(db,'crateReplacementRates'),orderBy('effectiveFrom','desc'))),getDocs(query(collection(db,'crateReconDaily'),orderBy('reconDate','desc')))]);setRates(rateSnap.docs.map(d=>({id:d.id,...d.data()} as ReplacementRate)));let rr=reconSnap.docs.map(d=>({id:d.id,...d.data()} as Recon)).filter(r=>validDate(r.reconDate));if(u?.userType==='edo'&&u.companyId)rr=rr.filter(r=>r.edoId===u.companyId);setRecons(rr);if(rr.length)setSelectedRoute(rr[0].routeNo)}catch(e){setError(e instanceof Error?e.message:'Unable to load crate reconciliation data.')}finally{setLoading(false)}})()},[]);
 const routes=useMemo(()=>[...new Set(recons.map(r=>r.routeNo))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[recons]);
 const routeRecons=useMemo(()=>recons.filter(r=>r.routeNo===selectedRoute).sort((a,b)=>b.reconDate.localeCompare(a.reconDate)),[recons,selectedRoute]);
 const current=routeRecons[0]||null;
 useEffect(()=>{if(current){setToDate(current.reconDate);setFromDate(daysBefore(current.reconDate,6))}else{setToDate('');setFromDate('')}},[selectedRoute,current?.reconDate]);
 const history=useMemo(()=>routeRecons.filter(r=>(!fromDate||r.reconDate>=fromDate)&&(!toDate||r.reconDate<=toDate)),[routeRecons,fromDate,toDate]);
 const rateFor=(date:string)=>rates.find(r=>r.effectiveFrom<=date)??null;
 const rate=useMemo(()=>current?rateFor(current.reconDate):null,[rates,current]);
 const crate=current?.crate??{allowance:0,previousOutstanding:0,issuedToday:0,returnedToday:0,currentOutstanding:0};const dolly=current?.dolly??{previousOutstanding:0,issuedToday:0,returnedToday:0,currentOutstanding:0};
 const crateCost=Number(rate?.crateCost??0),dollyCost=Number(rate?.dollyCost??0),short=Math.max(0,crate.previousOutstanding-crate.allowance),exposure=short*crateCost,within=short===0,util=crate.allowance?crate.previousOutstanding/crate.allowance*100:0;
 function downloadHistory(){if(!history.length)return;const headers=['Date','Route','Premier EDO / Driver Name','Site','Crate Previous','Crate OUT','Crate IN','Crate Current','Allowance','Crates Short','Crate Replacement Cost','Potential Charge Exposure','Dolly Previous','Dolly OUT','Dolly IN','Dolly Current','Dolly Replacement Cost'];const lines=[headers.map(csvCell).join(',')];for(const r of [...history].reverse()){const rr=rateFor(r.reconDate),cc=Number(rr?.crateCost??0),dc=Number(rr?.dollyCost??0),s=Math.max(0,r.crate.previousOutstanding-r.crate.allowance);lines.push([r.reconDate,r.routeNo,r.sourceName??'',r.site??'',r.crate.previousOutstanding,r.crate.issuedToday,r.crate.returnedToday,r.crate.currentOutstanding,r.crate.allowance,s,cc,s*cc,r.dolly.previousOutstanding,r.dolly.issuedToday,r.dolly.returnedToday,r.dolly.currentOutstanding,dc].map(csvCell).join(','))}const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`crate-dolly-recon_${selectedRoute}_${fromDate||'start'}_${toDate||'latest'}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
 if(loading)return<div className="flex min-h-64 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin"/></div>;
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><Button asChild variant="ghost" className="-ml-3"><Link href="/dashboard"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Dashboard</Link></Button><div className="flex gap-2">{user?.userType==='taskraft'&&<Button asChild variant="outline"><Link href="/accounting/crate-control/upload"><FileSpreadsheet className="mr-2 h-4 w-4"/>Upload Premier Recon</Link></Button>}{user?.accessLevel==='superadmin'&&<Button asChild variant="outline"><Link href="/accounting/crate-control/settings"><Settings className="mr-2 h-4 w-4"/>Replacement Costs</Link></Button>}</div></div>
 <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Crate & Dolly Control</h1><p className="text-muted-foreground">Live Premier reconciliation positions from imported recon data.</p></div>{current&&<div className="rounded-lg border bg-background px-4 py-2 text-sm"><span className="text-muted-foreground">Latest position:</span> <b>{prettyDate(current.reconDate)}</b></div>}</div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 {!current?<Card><CardContent className="py-12 text-center"><FileSpreadsheet className="mx-auto mb-3 h-9 w-9 text-muted-foreground"/><div className="text-lg font-semibold">No Premier reconciliation imported yet</div></CardContent></Card>:<><Card><CardContent className="flex flex-wrap items-end gap-4 pt-6"><div className="min-w-[220px] flex-1"><label className="text-sm font-medium">Route</label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={selectedRoute} onChange={e=>setSelectedRoute(e.target.value)}>{routes.map(r=><option key={r} value={r}>{r}</option>)}</select></div><div className="min-w-[220px] flex-1"><div className="text-xs uppercase text-muted-foreground">Premier EDO / Driver Name</div><div className="mt-2 font-semibold">{current.sourceName||'—'}</div></div><div><div className="text-xs uppercase text-muted-foreground">Site</div><div className="mt-2 font-semibold capitalize">{current.site||'—'}</div></div></CardContent></Card>
 {within?<Card className="border-emerald-300 bg-emerald-50"><CardContent className="flex items-center gap-3 pt-6 text-emerald-800"><ShieldCheck className="h-7 w-7"/><div><div className="text-sm font-semibold uppercase">Within Crate Allowance</div><div className="text-3xl font-bold">{Math.max(0,crate.allowance-crate.previousOutstanding)} crates available</div><div className="text-sm">Potential Charge Exposure: {money(0)}</div></div></CardContent></Card>:<Card className="border-red-300 bg-red-50"><CardContent className="flex flex-col gap-4 pt-6 md:flex-row md:items-center md:justify-between"><div className="flex gap-3"><AlertTriangle className="h-7 w-7 text-red-700"/><div><div className="text-sm font-semibold uppercase text-red-700">Over Crate Allowance</div><div className="text-3xl font-bold text-red-700">{short} crates short</div><div className="text-sm text-red-800">Previous outstanding {crate.previousOutstanding} minus allowance {crate.allowance}.</div></div></div><div className="md:text-right"><div className="text-sm font-medium text-red-700">Potential Charge Exposure</div><div className="text-4xl font-bold text-red-700">{money(exposure)}</div><div className="text-xs text-red-700">{crateCost?`${short} × ${money(crateCost)} replacement cost`:'No applicable replacement cost configured'}</div><div className="text-xs text-red-700">Indicative risk only — not an actual Premier charge.</div></div></CardContent></Card>}
 <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Crates</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Previous',crate.previousOutstanding],['Issued',crate.issuedToday],['Returned',crate.returnedToday],['Current',crate.currentOutstanding]].map(([a,b])=><div key={String(a)} className="rounded-xl border p-4"><div className="text-xs text-muted-foreground">{a}</div><div className="text-2xl font-bold">{b}</div></div>)}</div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-muted/40 p-4"><div className="text-xs text-muted-foreground">Allowance</div><div className="text-xl font-bold">{crate.allowance}</div></div><div className="rounded-xl bg-muted/40 p-4"><div className="text-xs text-muted-foreground">Utilisation</div><div className="text-xl font-bold">{util.toFixed(1)}%</div></div><div className="rounded-xl bg-muted/40 p-4"><div className="text-xs text-muted-foreground">Replacement Cost</div><div className="text-xl font-bold">{money(crateCost)}</div><div className="text-xs text-muted-foreground">{rate?`Effective ${prettyDate(rate.effectiveFrom)}`:'No applicable rate'}</div></div></div></CardContent></Card><Card><CardHeader><CardTitle>Dollies</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Previous',dolly.previousOutstanding],['Issued',dolly.issuedToday],['Returned',dolly.returnedToday],['Current',dolly.currentOutstanding]].map(([a,b])=><div key={String(a)} className="rounded-xl border p-4"><div className="text-xs text-muted-foreground">{a}</div><div className="text-2xl font-bold">{b}</div></div>)}</div><div className="rounded-xl bg-muted/40 p-4"><div className="text-xs text-muted-foreground">Dolly Replacement Cost</div><div className="text-xl font-bold">{money(dollyCost)}</div><div className="text-xs text-muted-foreground">{rate?`Effective ${prettyDate(rate.effectiveFrom)}`:'No applicable rate'}</div></div></CardContent></Card></div>
 <Card><CardHeader><div className="flex flex-wrap items-end justify-between gap-4"><div><CardTitle>Reconciliation History — {selectedRoute}</CardTitle><CardDescription>Defaults to the latest 7 calendar days. Select any date range and download the displayed history.</CardDescription></div><div className="flex flex-wrap items-end gap-2"><div><label className="text-xs font-medium text-muted-foreground">From</label><input type="date" className="mt-1 block h-9 rounded-md border bg-background px-2 text-sm" value={fromDate} max={toDate||undefined} onChange={e=>setFromDate(e.target.value)}/></div><div><label className="text-xs font-medium text-muted-foreground">To</label><input type="date" className="mt-1 block h-9 rounded-md border bg-background px-2 text-sm" value={toDate} min={fromDate||undefined} onChange={e=>setToDate(e.target.value)}/></div><Button variant="outline" onClick={downloadHistory} disabled={!history.length}><Download className="mr-2 h-4 w-4"/>Download CSV</Button></div></div></CardHeader><CardContent>{history.length===0?<div className="rounded-lg border bg-muted/30 p-6 text-center text-sm text-muted-foreground">No reconciliation records in the selected date range.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-3 text-left">Date</th><th className="text-right">Crate Previous</th><th className="text-right">Crate OUT</th><th className="text-right">Crate IN</th><th className="text-right">Crate Current</th><th className="text-right">Allowance</th><th className="text-right">Short</th><th className="text-right">Exposure</th><th className="text-right">Dolly Previous</th><th className="text-right">Dolly OUT</th><th className="text-right">Dolly IN</th><th className="pr-3 text-right">Dolly Current</th></tr></thead><tbody>{history.map(r=>{const s=Math.max(0,r.crate.previousOutstanding-r.crate.allowance),rr=rateFor(r.reconDate),e=s*Number(rr?.crateCost??0);return<tr key={r.id} className="border-b"><td className="p-3 font-medium">{prettyDate(r.reconDate)}</td><td className="text-right">{r.crate.previousOutstanding}</td><td className="text-right">{r.crate.issuedToday}</td><td className="text-right">{r.crate.returnedToday}</td><td className="text-right font-semibold">{r.crate.currentOutstanding}</td><td className="text-right">{r.crate.allowance}</td><td className={`text-right font-semibold ${s?'text-red-700':'text-emerald-700'}`}>{s}</td><td className={`text-right font-semibold ${s?'text-red-700':''}`}>{money(e)}</td><td className="text-right">{r.dolly.previousOutstanding}</td><td className="text-right">{r.dolly.issuedToday}</td><td className="text-right">{r.dolly.returnedToday}</td><td className="pr-3 text-right font-semibold">{r.dolly.currentOutstanding}</td></tr>})}</tbody></table></div>}</CardContent></Card></>}
 </div>;
}
