'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { addDoc, collection, getDocs, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { ArrowLeft, Loader2, Save } from 'lucide-react';
import { db } from '@/lib/firebase';
import { getCurrentUser, SessionUser } from '@/lib/session';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import NoAccess from '@/components/no-access';

type Rate={id:string;crateCost:number;dollyCost:number;effectiveFrom:string;createdByName?:string;createdAt?:any};
const money=(v:number)=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',minimumFractionDigits:2}).format(v||0);
export default function CrateControlSettingsPage(){const[user,setUser]=useState<SessionUser|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[rates,setRates]=useState<Rate[]>([]),[crateCost,setCrateCost]=useState(''),[dollyCost,setDollyCost]=useState(''),[effectiveFrom,setEffectiveFrom]=useState(''),[message,setMessage]=useState('');
 async function loadRates(){const s=await getDocs(query(collection(db,'crateReplacementRates'),orderBy('effectiveFrom','desc')));setRates(s.docs.map(d=>({id:d.id,...d.data()} as Rate)))}
 useEffect(()=>{(async()=>{try{const u=await getCurrentUser();setUser(u);if(u?.accessLevel==='superadmin')await loadRates()}finally{setLoading(false)}})()},[]);
 async function save(){if(!user||user.accessLevel!=='superadmin')return;const c=Number(crateCost),d=Number(dollyCost);if(!effectiveFrom||c<0||d<0||Number.isNaN(c)||Number.isNaN(d)){setMessage('Enter valid crate and dolly costs and an effective date.');return}setSaving(true);setMessage('');try{await addDoc(collection(db,'crateReplacementRates'),{crateCost:c,dollyCost:d,effectiveFrom,createdAt:serverTimestamp(),createdBy:user.uid,createdByName:user.name});setCrateCost('');setDollyCost('');setEffectiveFrom('');await loadRates();setMessage('Replacement costs saved. Historical rates remain unchanged.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save replacement costs.')}finally{setSaving(false)}}
 if(loading)return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin"/></div>;if(!user||user.accessLevel!=='superadmin')return <NoAccess/>;
 return <div className="space-y-6"><Button asChild variant="ghost" className="-ml-3"><Link href="/accounting/crate-control"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Crate & Dolly Control</Link></Button><div><h1 className="text-3xl font-bold">Crate & Dolly Replacement Costs</h1><p className="text-muted-foreground">Superadmin only. Rates are effective-dated and used for indicative exposure calculations.</p></div><Card><CardHeader><CardTitle>Add Replacement Cost</CardTitle><CardDescription>Add a new rate when Premier changes the replacement cost. Do not overwrite historical rates.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><label className="space-y-1"><span className="text-sm font-medium">Crate cost</span><input type="number" min="0" step="0.01" className="h-10 w-full rounded-md border bg-background px-3" value={crateCost} onChange={e=>setCrateCost(e.target.value)} placeholder="0.00"/></label><label className="space-y-1"><span className="text-sm font-medium">Dolly cost</span><input type="number" min="0" step="0.01" className="h-10 w-full rounded-md border bg-background px-3" value={dollyCost} onChange={e=>setDollyCost(e.target.value)} placeholder="0.00"/></label><label className="space-y-1"><span className="text-sm font-medium">Effective from</span><input type="date" className="h-10 w-full rounded-md border bg-background px-3" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)}/></label><div className="md:col-span-3 flex items-center gap-3"><Button onClick={save} disabled={saving}>{saving?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Save className="mr-2 h-4 w-4"/>}Save Rate</Button>{message&&<span className="text-sm text-muted-foreground">{message}</span>}</div></CardContent></Card><Card><CardHeader><CardTitle>Replacement Cost History</CardTitle><CardDescription>The applicable rate will be selected by reconciliation date.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b bg-muted/40 text-left"><th className="p-3">Effective From</th><th className="text-right">Crate Cost</th><th className="text-right">Dolly Cost</th><th className="pl-6">Added By</th></tr></thead><tbody>{rates.length?rates.map(r=><tr key={r.id} className="border-b"><td className="p-3 font-medium">{r.effectiveFrom}</td><td className="text-right">{money(Number(r.crateCost||0))}</td><td className="text-right">{money(Number(r.dollyCost||0))}</td><td className="pl-6">{r.createdByName||'—'}</td></tr>):<tr><td colSpan={4} className="p-8 text-center text-muted-foreground">No replacement costs loaded yet.</td></tr>}</tbody></table></div></CardContent></Card></div>}
